# Generated by Django 4.2.4 on 2023-08-29 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویدئو')),
                ('video', models.FileField(upload_to='', verbose_name='ویدئو')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('blog_text', models.TextField(verbose_name='متن مقاله')),
                ('blog_summery', models.TextField(verbose_name='خلاصه مقاله')),
                ('main_img', models.ImageField(default=None, upload_to='images/blogimg', verbose_name='تصویر')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('user_registered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
