# Generated by Django 4.2.4 on 2023-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_img',
            field=models.ImageField(default=None, upload_to='images/blogimg/', verbose_name='تصویر'),
        ),
    ]
