# Generated by Django 4.2.4 on 2023-08-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_blog_summery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_summery',
            field=models.TextField(max_length=500, verbose_name='خلاصه مقاله'),
        ),
    ]
