# Generated by Django 4.2.4 on 2023-09-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_videos_is_active_videos_poster_videos_register_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('resume', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='images/counselimg/')),
            ],
        ),
    ]
