# Generated by Django 4.2.4 on 2023-09-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='poster',
            field=models.ImageField(default=None, upload_to='images/videoposter/', verbose_name='پوستر ویدئو'),
        ),
    ]
