# Generated by Django 4.2.4 on 2023-08-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('ress1', models.IntegerField()),
                ('ress2', models.IntegerField()),
                ('ress3', models.IntegerField()),
                ('ress4', models.IntegerField()),
                ('ress5', models.IntegerField()),
                ('ress6', models.IntegerField()),
                ('ress7', models.IntegerField()),
                ('ress8', models.IntegerField()),
            ],
        ),
    ]
